# Generated by Django 4.0.4 on 2022-05-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'ຄະນິດສາດ'), ('sci', 'ວິທະຍາສາດ'), ('art', 'ສີລະປະ'), ('eng', 'ພາສາອັງກິດ'), ('physics', 'ຟີຊິກ'), ('bio', 'ຊີວະສາດ')], default='math', max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
